/* eslint-disable */
/**
 * Generated API - This is a placeholder for the demo.
 * In a real app, this would be generated by `convex dev`.
 */

import type { Id } from 'convex/values';

// Types for tasks table
export interface Task {
  _id: Id<'tasks'>;
  _creationTime: number;
  text: string;
  completed: boolean;
  createdAt: number;
}

// API type definition
export const api = {
  tasks: {
    list: 'tasks:list' as any,
    add: 'tasks:add' as any,
    toggle: 'tasks:toggle' as any,
    remove: 'tasks:remove' as any,
  },
};
