name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-*'

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  BINARY_NAME: dx

jobs:
  # Create release
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Get version from tag
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: Generate changelog
        id: changelog
        run: |
          echo "## What's Changed" > CHANGELOG.md
          echo "" >> CHANGELOG.md
          git log --pretty=format:"- %s (%h)" $(git describe --tags --abbrev=0 HEAD^)..HEAD >> CHANGELOG.md || true
      
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: DX v${{ steps.get_version.outputs.version }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: ${{ contains(github.ref, '-') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Build for each platform
  build-release:
    name: Build (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux x64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact: dx-linux-x64
            archive: tar.gz
          
          # Linux ARM64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            artifact: dx-linux-arm64
            archive: tar.gz
            cross: true
          
          # Linux musl (static)
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            artifact: dx-linux-x64-musl
            archive: tar.gz
            cross: true
          
          # macOS x64
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact: dx-macos-x64
            archive: tar.gz
          
          # macOS ARM64 (Apple Silicon)
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact: dx-macos-arm64
            archive: tar.gz
          
          # Windows x64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact: dx-windows-x64
            archive: zip
          
          # Windows ARM64
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            artifact: dx-windows-arm64
            archive: zip

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-action@stable
        with:
          targets: ${{ matrix.target }}
      
      - name: Install cross (Linux)
        if: matrix.cross
        run: cargo install cross --locked
      
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Build (native)
        if: ${{ !matrix.cross }}
        run: cargo build --release --locked --target ${{ matrix.target }}
      
      - name: Build (cross)
        if: matrix.cross
        run: cross build --release --locked --target ${{ matrix.target }}
      
      - name: Strip binary (Unix)
        if: runner.os != 'Windows'
        run: |
          strip target/${{ matrix.target }}/release/${{ env.BINARY_NAME }} || true
      
      - name: Create archive (tar.gz)
        if: matrix.archive == 'tar.gz'
        run: |
          cd target/${{ matrix.target }}/release
          tar -czvf ../../../${{ matrix.artifact }}.tar.gz ${{ env.BINARY_NAME }}
      
      - name: Create archive (zip)
        if: matrix.archive == 'zip'
        shell: pwsh
        run: |
          cd target/${{ matrix.target }}/release
          Compress-Archive -Path ${{ env.BINARY_NAME }}.exe -DestinationPath ../../../${{ matrix.artifact }}.zip
      
      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.artifact }}.${{ matrix.archive }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Build and publish Docker image
  docker-release:
    name: Docker Release
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            dxcli/dx
            ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Publish to crates.io
  cargo-publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    needs: [create-release, build-release]
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-action@stable
      
      - name: Publish to crates.io
        run: |
          cargo publish --dry-run -p dx-serializer || true
          # Uncomment when ready:
          # cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }} -p dx-serializer
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  # Update Homebrew formula
  homebrew-update:
    name: Update Homebrew
    runs-on: ubuntu-latest
    needs: [build-release]
    steps:
      - name: Update Homebrew formula
        run: |
          echo "Homebrew formula update would go here"
          echo "VERSION=${{ needs.create-release.outputs.version }}"
          # This would typically create a PR to a homebrew-tap repo

  # Notify release
  notify:
    name: Notify Release
    runs-on: ubuntu-latest
    needs: [create-release, build-release, docker-release]
    if: always()
    steps:
      - name: Send notification
        run: |
          echo "## Release Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Version**: ${{ needs.create-release.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Build Status**: ${{ needs.build-release.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Docker Status**: ${{ needs.docker-release.result }}" >> $GITHUB_STEP_SUMMARY
