"""Type stubs for sample module."""

from typing import List

class Calculator:
    value: float
    history: List[str]

    def __init__(self, initial_value: float = ...) -> None: ...
    def add(self, x: float) -> Calculator: ...
    def subtract(self, x: float) -> Calculator: ...
    def multiply(self, x: float) -> Calculator: ...
    def divide(self, x: float) -> Calculator: ...
    def reset(self) -> Calculator: ...
    def get_history(self) -> List[str]: ...

def fibonacci(n: int) -> List[int]: ...
def main() -> None: ...
