//! Error types for RLM operations.
//!
//! This module defines all error types that can occur during RLM execution,
//! including LLM API errors, REPL execution errors, and parsing errors.

use thiserror::Error;

/// Result type alias for RLM operations.
pub type Result<T> = std::result::Result<T, RLMError>;

/// Errors that can occur during RLM execution.
#[derive(Error, Debug)]
pub enum RLMError {
    /// Maximum iteration limit exceeded during execution.
    ///
    /// This occurs when the RLM reaches the configured maximum number of
    /// iterations without finding a FINAL() answer.
    #[error("Max iterations ({0}) exceeded - consider increasing max_iterations or simplifying the query")]
    MaxIterations(usize),

    /// Maximum recursion depth exceeded.
    ///
    /// This prevents infinite recursion by limiting the depth of recursive calls.
    #[error("Max recursion depth ({0}) exceeded - reduce query complexity or increase max_depth")]
    MaxDepth(usize),

    /// Error during REPL code execution.
    ///
    /// This occurs when the Rhai script generated by the LLM fails to compile or execute.
    #[error("REPL execution error: {0}")]
    REPLError(String),

    /// Error from the LLM API.
    ///
    /// This includes network errors, authentication failures, and API-specific errors.
    #[error("LLM API error: {0}")]
    LLMError(String),

    /// Error parsing LLM response.
    ///
    /// This occurs when the LLM response doesn't match expected formats.
    #[error("Parse error: {0}")]
    ParseError(String),

    /// HTTP request error.
    #[error("HTTP error: {0}")]
    HttpError(#[from] reqwest::Error),

    /// JSON serialization/deserialization error.
    #[error("JSON error: {0}")]
    JsonError(#[from] serde_json::Error),

    /// Rhai script execution error.
    #[error("Rhai error: {0}")]
    RhaiError(#[from] Box<rhai::EvalAltResult>),

    /// File I/O error.
    #[error("IO error: {0}")]
    IoError(#[from] std::io::Error),
}
