//! GitHub submission for plugin publishing.
//!
//! Handles creating pull requests to the dx-plugins repository
//! for plugin submission and review.

use std::path::Path;

/// GitHub submission handler.
#[derive(Debug)]
pub struct GitHubSubmission {
    /// Target repository (owner/repo)
    repo: String,
    /// GitHub personal access token
    token: Option<String>,
    /// Base branch to create PR against
    base_branch: String,
    /// Whether to enable auto-merge
    auto_merge: bool,
}

impl GitHubSubmission {
    /// Create a new GitHub submission handler.
    pub fn new(repo: impl Into<String>) -> Self {
        Self {
            repo: repo.into(),
            token: None,
            base_branch: String::from("main"),
            auto_merge: true,
        }
    }

    /// Set the GitHub token.
    pub fn with_token(mut self, token: impl Into<String>) -> Self {
        self.token = Some(token.into());
        self
    }

    /// Set the base branch.
    pub fn with_base_branch(mut self, branch: impl Into<String>) -> Self {
        self.base_branch = branch.into();
        self
    }

    /// Disable auto-merge.
    pub fn no_auto_merge(mut self) -> Self {
        self.auto_merge = false;
        self
    }

    /// Submit a plugin package for review.
    ///
    /// This creates a pull request with the plugin files.
    pub async fn submit(
        &self,
        package_path: &Path,
        manifest: &PluginInfo,
    ) -> Result<PullRequest, SubmissionError> {
        // Validate inputs
        if !package_path.exists() {
            return Err(SubmissionError::PackageNotFound(package_path.to_path_buf()));
        }

        if self.token.is_none() {
            return Err(SubmissionError::MissingToken);
        }

        // Generate branch name
        let branch_name =
            format!("plugin/{}-{}", manifest.name, manifest.version.replace('.', "-"));

        // In production, this would:
        // 1. Fork the repository (if needed)
        // 2. Create a new branch
        // 3. Add the plugin files
        // 4. Create a pull request

        let pr = PullRequest {
            number: 0, // Would be set by GitHub API
            url: format!("https://github.com/{}/pull/new/{}", self.repo, branch_name),
            title: format!("Add plugin: {} v{}", manifest.name, manifest.version),
            body: self.generate_pr_body(manifest),
            branch: branch_name,
            status: SubmissionStatus::Pending,
            auto_merge_enabled: self.auto_merge,
        };

        Ok(pr)
    }

    /// Generate PR body text.
    fn generate_pr_body(&self, manifest: &PluginInfo) -> String {
        format!(
            r#"## Plugin Submission

### Details
- **Name**: {}
- **Version**: {}
- **Description**: {}
- **Author**: {} ({})

### Checklist
- [ ] Plugin passes all validation checks
- [ ] Documentation is complete
- [ ] Tests are included
- [ ] No security vulnerabilities detected

### Auto-merge
{}

---
*This PR was automatically generated by `dx forge publish`*
"#,
            manifest.name,
            manifest.version,
            manifest.description,
            manifest.author_name,
            manifest.author_email,
            if self.auto_merge {
                "This PR will be automatically merged when all checks pass."
            } else {
                "Manual review required before merge."
            }
        )
    }

    /// Check the status of a submitted PR.
    pub async fn check_status(&self, _pr_number: u32) -> Result<SubmissionStatus, SubmissionError> {
        // In production, this would query the GitHub API
        Ok(SubmissionStatus::Pending)
    }

    /// Enable auto-merge on a PR.
    pub async fn enable_auto_merge(&self, _pr_number: u32) -> Result<(), SubmissionError> {
        if self.token.is_none() {
            return Err(SubmissionError::MissingToken);
        }

        // In production, this would call the GitHub GraphQL API
        // to enable auto-merge on the PR

        Ok(())
    }
}

/// Plugin information for submission.
#[derive(Debug, Clone)]
pub struct PluginInfo {
    /// Plugin name
    pub name: String,
    /// Plugin version
    pub version: String,
    /// Plugin description
    pub description: String,
    /// Author name
    pub author_name: String,
    /// Author email
    pub author_email: String,
    /// GitHub username
    pub github_username: Option<String>,
}

impl PluginInfo {
    /// Create new plugin info.
    pub fn new(name: impl Into<String>, version: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            version: version.into(),
            description: String::new(),
            author_name: String::new(),
            author_email: String::new(),
            github_username: None,
        }
    }
}

/// Pull request information.
#[derive(Debug, Clone)]
pub struct PullRequest {
    /// PR number
    pub number: u32,
    /// PR URL
    pub url: String,
    /// PR title
    pub title: String,
    /// PR body/description
    pub body: String,
    /// Source branch
    pub branch: String,
    /// Current status
    pub status: SubmissionStatus,
    /// Whether auto-merge is enabled
    pub auto_merge_enabled: bool,
}

impl PullRequest {
    /// Get a formatted status message.
    pub fn status_message(&self) -> String {
        match self.status {
            SubmissionStatus::Pending => "⏳ Waiting for CI checks".into(),
            SubmissionStatus::ChecksPassing => "✓ All checks passing".into(),
            SubmissionStatus::ChecksFailing => "✗ Some checks failing".into(),
            SubmissionStatus::Merged => "🎉 Merged!".into(),
            SubmissionStatus::Closed => "❌ Closed".into(),
            SubmissionStatus::Draft => "📝 Draft".into(),
        }
    }
}

/// Status of a plugin submission.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SubmissionStatus {
    /// PR created, waiting for checks
    Pending,
    /// All CI checks passing
    ChecksPassing,
    /// Some CI checks failing
    ChecksFailing,
    /// PR has been merged
    Merged,
    /// PR has been closed without merge
    Closed,
    /// PR is in draft state
    Draft,
}

/// Errors that can occur during submission.
#[derive(Debug, thiserror::Error)]
pub enum SubmissionError {
    #[error("Package not found: {0}")]
    PackageNotFound(std::path::PathBuf),

    #[error("GitHub token not provided")]
    MissingToken,

    #[error("GitHub API error: {0}")]
    ApiError(String),

    #[error("Network error: {0}")]
    NetworkError(String),

    #[error("Repository not found: {0}")]
    RepoNotFound(String),

    #[error("Authentication failed")]
    AuthFailed,

    #[error("Rate limit exceeded")]
    RateLimited,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_github_submission_new() {
        let submission = GitHubSubmission::new("dx-ecosystem/dx-plugins");
        assert_eq!(submission.repo, "dx-ecosystem/dx-plugins");
        assert_eq!(submission.base_branch, "main");
        assert!(submission.auto_merge);
    }

    #[test]
    fn test_plugin_info() {
        let info = PluginInfo::new("test-plugin", "1.0.0");
        assert_eq!(info.name, "test-plugin");
        assert_eq!(info.version, "1.0.0");
    }

    #[test]
    fn test_submission_status_message() {
        let pr = PullRequest {
            number: 1,
            url: String::new(),
            title: String::new(),
            body: String::new(),
            branch: String::new(),
            status: SubmissionStatus::ChecksPassing,
            auto_merge_enabled: true,
        };
        assert!(pr.status_message().contains("passing"));
    }

    #[test]
    fn test_pr_body_generation() {
        let submission = GitHubSubmission::new("test/repo");
        let info = PluginInfo {
            name: "my-plugin".into(),
            version: "1.0.0".into(),
            description: "A test plugin".into(),
            author_name: "Test Author".into(),
            author_email: "test@example.com".into(),
            github_username: Some("testuser".into()),
        };

        let body = submission.generate_pr_body(&info);
        assert!(body.contains("my-plugin"));
        assert!(body.contains("1.0.0"));
        assert!(body.contains("Test Author"));
    }
}
