//! `forge vibe-demo`
//!
//! Creates a tiny demo project with one file per media type and actually runs
//! init → add → commit → push --mirror all-free end-to-end.
//! The output is the launch tweet screen recording.
use anyhow::{Context, Result};
use std::fs;

use crate::cli;

pub fn run() -> Result<()> {
    let tmp = std::env::temp_dir().join("forge-vibe-demo");
    if tmp.exists() {
        fs::remove_dir_all(&tmp).ok();
    }
    fs::create_dir_all(&tmp)?;

    // Minimal valid-ish placeholder bytes so mime detection works
    fs::write(tmp.join("god_tier_fight_scene.mp4"),  b"\x00\x00\x00\x18ftypmp42")?;
    fs::write(tmp.join("thumbnail.png"),              b"\x89PNG\r\n\x1a\n")?;
    fs::write(tmp.join("soundtrack.mp3"),             b"ID3")?;
    fs::write(tmp.join("character_rig.glb"),          b"glTF")?;
    fs::write(tmp.join("README.md"), b"# Forge Vibe Demo\n\nGenerated by `forge vibe-demo`.\n")?;

    println!();
    println!("  forge vibe-demo — demo project");
    println!("  ──────────────────────────────");
    println!("  Location: {}", tmp.display());
    println!();
    println!("  Files:");
    println!("    god_tier_fight_scene.mp4   → YouTube  (private, unlimited)");
    println!("    thumbnail.png              → Pinterest (secret pin)");
    println!("    soundtrack.mp3             → SoundCloud (private track)");
    println!("    character_rig.glb          → Sketchfab (private model)");
    println!("    README.md                  → GitHub  (private repo)");
    println!();

    // cd into the demo directory so all forge commands run there
    std::env::set_current_dir(&tmp).context("cd into demo dir")?;

    // Step 1: init
    println!("  ─── forge init . ───");
    cli::init::run(".")?;
    println!();

    // Step 2: add all files
    println!("  ─── forge add . ───");
    let paths = vec![".".to_string()];
    cli::add::run(&paths, false)?;
    println!();

    // Step 3: commit
    println!("  ─── forge commit -m \"v42 god tier fight scene\" ───");
    cli::commit::run("v42 god tier fight scene")?;
    println!();

    // Step 4: push --mirror all-free
    println!("  ─── forge push --mirror all-free ───");
    match cli::push::run("origin", Some("all-free"), false) {
        Ok(()) => {}
        Err(e) => {
            // If no backends are authed, that's fine for the demo — show the user
            eprintln!("  ⚠ Push did not complete: {e}");
            println!();
            println!("  No backends authenticated? Run these first:");
            println!("    forge auth youtube");
            println!("    forge auth pinterest");
            println!("    forge auth soundcloud");
            println!("    forge auth sketchfab");
            println!("    forge auth github");
            println!("  Then re-run: cd \"{}\" && forge push --mirror all-free", tmp.display());
        }
    }

    println!();
    println!("  That's it. No credit card. No storage limits. Just Forge.");
    println!();

    Ok(())
}
